### ISSUE TITLE
Generate a requirements.txt

### ISSUE THREAD

**Issue by uncared** [kittiescaties/discord-boost-bot#21]
I Don't employ Discord boost bots because I abide by the Terms of Service, but why not make a requirements.txt instead of making people execute various commands? It simplifies things for a public repository.

**Comment by kittiescaties** [comment]
I did not make this I have just copied the files since people wanted to sell it for an insane amount.

**Comment by uncared** [comment]
> I did not make this I have just copied the files since people wanted to sell it for an insane amount.

Oh alright.
