### ISSUE TITLE
help please 

### ISSUE THREAD

**Issue by 3xyd** [kittiescaties/discord-boost-bot#24]
line 38, in <module>
    bot = discord.Bot(command_prefix="*", activity=activity, status=discord.Status.online)
          ^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by Jaydenha09** [comment]
do these command
pip uninstall pycord

pip uninstall discord.py

pip uninstall discord

pip install -U git+https://github.com/Pycord-Development/pycord

**Comment by 3xyd** [comment]
> do these command
> 
> pip uninstall pycord
> 
> pip uninstall discord.py
> 
> pip uninstall discord
> 
> pip install -U git+https://github.com/Pycord-Development/pycord

still the same error

**Comment by Xia3412** [comment]
At the starting of your .py script import the commands from discord.ext. Just paste this at the top of your code:

from discord.ext import commands

Then replace the discord.Bot with commands.Bot and you should be good to go

**Comment by Jaydenha09** [comment]
you can install older versions of pycord to fix it by this command

pip install py-cord===2.2

**Comment by 3xyd** [comment]
can you pleaase tell me how to setup the discord bot and what do i need to set up in bot ?

**Comment by 3xyd** [comment]
14:20:22 [+] Discord Bot is online!
Traceback (most recent call last):
  File "C:\Users\ashan\OneDrive\Desktop\New folder (3)\4\main.py", line 41, in <module>
    @bot.slash_command(
     ^^^
NameError: name 'bot' is not defined

**Comment by 3xyd** [comment]
@Jaydenha09 @kittiescaties anyhelp

**Comment by kittiescaties** [comment]
It might be an error with the bot itself as the discord api changes as so do the modules.

**Comment by Jaydenha09** [comment]
here is the fixed one
https://mega.nz/file/5YxACaZD#kRDFDPMZmEN7aX0ArZwtLJFwKE50HQbnADkTKsVMS4A
It is working for me and discord didn’t make any changes on it that will break it
