### ISSUE TITLE
isue with ngrok

### ISSUE THREAD

**Issue by zoomswrld** [kittiescaties/discord-boost-bot#4]
I try and get my webhook url but it doesnt match .io and I tried to use the one before the arrow and put it in like below. Pls tell me if im wrong. I get all these errors. Can someone pls help.
![Screenshot 2023-04-29 180644](https://user-images.githubusercontent.com/129002328/235329081-ea00ba23-b64a-4024-8c7c-cd5400d31257.png)
![Screenshot 2023-04-29 180755](https://user-images.githubusercontent.com/129002328/235329114-fe4ebcad-ef7f-4333-bb26-d2cab573d5f5.png)
![Screenshot 2023-04-29 180805](https://user-images.githubusercontent.com/129002328/235329118-075bf00b-82de-4dc4-b248-f240a31758b8.png)

**Comment by kittiescaties** [comment]
Remove the brackets
