### ISSUE TITLE
Hey mine just opens and closes why is that?

### ISSUE THREAD

**Issue by PsxScriptsW** [kittiescaties/discord-boost-bot#6]

**Comment by PsxScriptsW** [comment]
<img width="792" alt="Screenshot 2023-06-02 150114" src="https://github.com/kittiescaties/discord-boost-bot/assets/103678475/7dd29f84-ebea-4845-80ee-306da4f55190">
This is the error what do i do

**Comment by kittiescaties** [comment]
This is caused by the discord module to fix install git and do this: pip install -U git+https://github.com/Pycord-Development/pycord

**Comment by PsxScriptsW** [comment]
Hey so uh when it boosts does it delete the tokens after?

**Comment by kittiescaties** [comment]
Yes it deletes the used tokens after you have boosted the server
