### ISSUE TITLE
Help again sorry

### ISSUE THREAD

**Issue by PsxScriptsW** [kittiescaties/discord-boost-bot#8]
look 
<img width="792" alt="Screenshot 2023-06-02 150114" src="https://github.com/kittiescaties/discord-boost-bot/assets/103678475/05c150ca-8c57-45ee-aacf-3877f548145f">

**Comment by PsxScriptsW** [comment]
nvm now its this
<img width="792" alt="Screenshot 2023-06-02 150114" src="https://github.com/kittiescaties/discord-boost-bot/assets/103678475/05c150ca-8c57-45ee-aacf-3877f548145f">

**Comment by PsxScriptsW** [comment]
and i did the py cord thing

**Comment by PsxScriptsW** [comment]
nvm i found the fix the fix is py -3 -m pip install -U py-cord

**Comment by kittiescaties** [comment]
alright!
